#!/bin/bash
set -e

# https://github.com/romanr/rebase-script
# Rebase script version 1.0
# Usage:
# Rebase current branch:
# rebase
# Rebase specific branch:
# rebase [branch name]

branch=`git rev-parse --abbrev-ref HEAD`
echo "Current branch: $branch"

if [ -z "$1" ] && [ "$branch" == "develop" ]
  then
    echo "Branch name parameter is missing."
    echo "Usage:"
    echo "$0 [branch name]"
    exit 1
fi

# rebase specified branch
if [ "$1" ] 
  then
branch=$1
fi

if ! [[ -z "$(git status --porcelain)" ]]; then
  echo "Working directory is not clean. Stash your changes first."
  exit 1
fi

echo "Preparing to rebase branch $branch on to develop..."
git fetch
git checkout develop
git pull
git show-branch $branch &>/dev/null && git checkout $branch || git checkout --track origin/$branch
git pull

echo 
echo "🔝 Rebase..."
git rebase develop
echo 
echo "❗️ If everything is okay, confirm force push $branch to remote:"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git push --force; break;;
        No ) exit;;
    esac
done
git checkout develop
echo 
echo "🚮 Delete branch $branch locally ?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git branch -d $branch; break;;
        No ) exit;;
    esac
done

